# Generated by Django 3.2.5 on 2021-07-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0002_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='media'),
        ),
    ]
