# Generated by Django 3.2.5 on 2021-07-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=150, null=True),
        ),
    ]
